### PR TITLE
Add optional message to display before password prompt

### PR DESCRIPTION
**Pull request by andrelaszlo**
This can be useful for greetings, QOTD, or laptop owner information

### CODE REVIEW

**Comment by andrelaszlo** [comment]
Sorry, used spaces instead of tabs! Will fix.

spaces!

**Comment by andrelaszlo** [comment]
Hi @muennich do you think this feature is something you'd like to add? I've been using it on my computer for three weeks now and I find it really convenient. Otherwise, feel free to close the PR! :)

**Comment by craftyguy** [comment]
This would be really cool, I hope it gets merged!

**Comment by muennich** [comment]
Thanks for your work.

I have altered your commit for the following: printing the message to the console not stdout, correct formatting in man page and alphabetic ordering of option characters.

**Comment by andrelaszlo** [comment]
Hooray! Thanks for fixing those things and for accepting my patch.

**Comment by andrelaszlo** [comment]
You're probably busy but would you mind also tagging a release? It makes it easier to upgrade the AUR package for Arch.

**Comment by muennich** [comment]
I'm the maintainer of the AUR package. I've just commented on issue #46 regarding the next stable release.

**Comment by andrelaszlo** [comment]
Haha, I see. Thanks again!

**Pull request closed without merging**
